# .github/workflows/convert-md-to-html.yml

# EXAMPLES:
# https://github.com/arnested/ldddns/blob/a8574e5445c6bb62a88b71dd338af169ac4c874a/.github/workflows/release.yml#L68

name: Markdown to HTML
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'buttons/**.md'
      - 'buttons/images/**'

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@master
        with:
          input_path: buttons/
          output_dir: site/
          images_dir: buttons/images
          build_html: true
          bulid_pdf: false
      - name: Upload HTML files
      - uses: actions/upload-artifact@v3
        with:
          name: HTML files
          path: pdfs
